### ISSUE TITLE
ReferenceError: `useClasses` is not defined

### ISSUE THREAD

**Issue by hikaru150s** [GeeekyBoy/Quine-McCluskey-Solver#2]
```
react-dom.production.min.js:189 ReferenceError: useClasses is not defined
    at Yn (PetrickMethod.js:8:19)
    at Pl (react-dom.production.min.js:167:137)
    at bu (react-dom.production.min.js:290:337)
    at yp (react-dom.production.min.js:280:389)
    at vp (react-dom.production.min.js:280:320)
    at Np (react-dom.production.min.js:280:180)
    at op (react-dom.production.min.js:271:88)
    at rp (react-dom.production.min.js:268:429)
    at T (scheduler.production.min.js:13:203)
    at MessagePort.G (scheduler.production.min.js:14:128)
di @ react-dom.production.min.js:189
n.callback @ react-dom.production.min.js:189
xo @ react-dom.production.min.js:144
Wu @ react-dom.production.min.js:262
yu @ react-dom.production.min.js:260
Su @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
qp @ react-dom.production.min.js:281
rp @ react-dom.production.min.js:270
T @ scheduler.production.min.js:13
G @ scheduler.production.min.js:14
```

Did it miss something [here](https://github.com/GeeekyBoy/Quine-McCluskey-Solver/blob/0bbd04fe2d42dc3de2c906b3facc84c02039a770/src/components/PetrickMethod.js#LL8C44-L8C44)?

**Comment by GeeekyBoy** [comment]
@hikaru150s It was working perfect. Anyway, I have just done heavy refactoring to the source code.
Can you please try to build the project again ?

**Comment by hikaru150s** [comment]
I see, the issue was disappeared after refactor commit. Gonna close this issue since no longer valid.

Anyway, good work you've done on this project. Really helpful for learning 👍
